add_newline = true
continuation_prompt = "[▸▹ ](dimmed blue)"
palette = "catppuccin_latte"

format = """(\
$nix_shell\
$container\
\n)\
(\
$os\
$username\
$hostname\
$localip\
$shell\
$shlvl\
$directory\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$git_metrics \
$fill \
$singularity\
$kubernetes\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
# $conda\
$meson\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$spack\
$memory_usage\
$custom\
$status\
$battery\
$time\
\n)\
$cmd_duration\
$vcsh\
$env_var\
$jobs\
$sudo\
$character\
"""

[fill]
symbol = ''

[nix_shell]
symbol = " "
style = 'bold dimmed blue'
format = '[$symbol nix⎪$state⎪]($style) [$name](dimmed blue)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed ellow)'

[os]
style = "fg:blue"
# disabled = true      # Disabled by default
disabled = false # Disabled by default

[username]
style_user = "bright-yellow bold"
style_root = "purple bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
format = '[$ssh_symbol$hostname]($style) '
ssh_symbol = " "
ssh_only = false

[localip]
ssh_only = true
format = " @[$localipv4](bold magenta)"
disabled = false

[shell]
bash_indicator = " "
fish_indicator = ' '
zsh_indicator = " "
ion_indicator = " "
cmd_indicator = " "
powershell_indicator = ' '
unknown_indicator = ' >_'
style = 'cyan bold'
disabled = false

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style) '
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0

[directory]
truncation_length = 4
truncation_symbol = " …/"
read_only = " 󰌾"
use_os_path_sep = true
style = "blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold bright-blue)'

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = " ~"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[fossil_branch]
symbol = " "

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
symbol = "󰊢 "
truncation_symbol = "⋯"
truncation_length = 11
# ignore_branches = ["main", "master"]
only_attached = true

[git_commit]
tag_symbol = '  '

[git_status]
style = "bold bright-blue"
# format = "[⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style)"
format = '[\($state( $progress_current of $progress_total)$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed\)]($style) '
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
conflicted = "[◪◦](bright-magenta)"
ahead = "[▴│[${count}](bold blue)│](green)"
behind = "[▿│[${count}](bold blue)│](red)"
diverged = "[◇ ▴┤[${ahead_count}](regular blue)│▿┤[${behind_count}](regular white)│](bright-magenta)"
untracked = "[◌◦](bright-yellow)"
stashed = "[◃◈](blue)"
modified = "[●◦](yellow)"
staged = "[▪┤[$count](bold blue)│](bright-cyan)"
renamed = "[◎◦](bright-blue)"
deleted = "[✕](red)"

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'dimmed green'
deleted_style = 'dimmed red'
ignore_submodules = true
disabled = false

[memory_usage]
symbol = " "
format = "$symbol[${ram}( ${swap})]($style)"
disabled = false
threshold = 70

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 60
style = "dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "dimmed yellow"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%D %r"
utc_time_offset = "local"
style = "dimmed blue"


[cmd_duration]
format = "[◄ $duration ](blue)"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green'

[jobs]
format = "[$symbol:$number]($style) "
style = "bold blue"
symbol = "[ bg](bold red)"

[sudo]
format = "[$symbol]($style)"
style = "bold bright-purple"
symbol = "󰻡 "
disabled = false

[character]
format = "$symbol"
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = "[■](dimmed green) "
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = "CachyOS "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true
format = '[ $symbol($version) ]($style)'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
