add_newline = true
continuation_prompt = "[▸▹ ](dimmed blue)"

format = """(\
$nix_shell\
$container\
\n)\
(\
$os\
$username\
$hostname\
$localip\
$shell\
$shlvl\
$directory\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$git_metrics \
$fill \
$singularity\
$kubernetes\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$spack\
$memory_usage\
$custom\
$status\
$battery\
$time\
\n)\
$cmd_duration\
$vcsh\
$env_var\
$jobs\
$sudo\
$character\
"""

[fill]
symbol = ''

[nix_shell]
symbol = " "
style = 'bold dimmed blue'
format = '[$symbol nix⎪$state⎪]($style) [$name](dimmed blue)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed ellow)'

[os]
style = "fg:blue"
# disabled = true      # Disabled by default
disabled = false # Disabled by default

[username]
style_user = "bright-yellow bold"
style_root = "purple bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
format = '[$ssh_symbol$hostname]($style) '
ssh_symbol = " "
ssh_only = false

[localip]
ssh_only = true
format = " @[$localipv4](bold magenta)"
disabled = false

[shell]
bash_indicator = " "
fish_indicator = ' '
zsh_indicator = " "
ion_indicator = " "
cmd_indicator = " "
powershell_indicator = ' '
unknown_indicator = ' >_'
style = 'cyan bold'
disabled = false

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style) '
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0

[directory]
truncation_length = 4
truncation_symbol = " …/"
read_only = " 󰌾"
use_os_path_sep = true
style = "blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold bright-blue)'

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = " ~"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[fossil_branch]
symbol = " "

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
symbol = "󰊢 "
truncation_symbol = "⋯"
truncation_length = 11
# ignore_branches = ["main", "master"]
only_attached = true

[git_commit]
tag_symbol = '  '

[git_status]
style = "bold bright-blue"
# format = "[⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style)"
format = '[\($state( $progress_current of $progress_total)$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed\)]($style) '
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
conflicted = "[◪◦](bright-magenta)"
ahead = "[▴│[${count}](bold blue)│](green)"
behind = "[▿│[${count}](bold blue)│](red)"
diverged = "[◇ ▴┤[${ahead_count}](regular blue)│▿┤[${behind_count}](regular white)│](bright-magenta)"
untracked = "[◌◦](bright-yellow)"
stashed = "[◃◈](blue)"
modified = "[●◦](yellow)"
staged = "[▪┤[$count](bold blue)│](bright-cyan)"
renamed = "[◎◦](bright-blue)"
deleted = "[✕](red)"

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'dimmed green'
deleted_style = 'dimmed red'
ignore_submodules = true
disabled = false

[memory_usage]
symbol = " "
format = "$symbol[${ram}( ${swap})]($style)"
disabled = false
threshold = 70

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 60
style = "dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "dimmed yellow"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%D %r"
utc_time_offset = "local"
style = "dimmed blue"


[cmd_duration]
format = "[◄ $duration ](blue)"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green'

[jobs]
format = "[$symbol:$number]($style) "
style = "bold blue"
symbol = "[ bg](bold red)"

[sudo]
format = "[$symbol]($style)"
style = "bold bright-purple"
symbol = "󰻡 "
disabled = false

[character]
format = "$symbol"
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
vimcmd_symbol = "[■](dimmed green) "
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = "CachyOS "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true
format = '[ $symbol($version) ]($style)'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
